# Generated by Django 5.1.2 on 2024-11-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
